import { moneyCents, vilniusCandidates } from './reliability.js?v=20261004-1';
export const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => new Intl.NumberFormat('en-GB',{style:'currency',currency:'EUR'}).format(Number(value || 0)/100);
const date = value => value ? new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Vilnius',dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : 'Unknown';
const hidden = (name,value) => `<input type="hidden" name="${name}" value="${esc(value)}">`;
const amountInput = (name,label,value='') => `<label>${label}<input name="${name}" type="text" inputmode="decimal" required value="${esc(value)}" placeholder="0.00"></label>`;
const formEnd = label => `<div class="admin-form-error" data-action-error role="status" aria-live="polite"></div><button class="admin-button admin-button-secondary" type="submit">${label}</button></form>`;
const latest = (operations,id) => (operations?.quotes || []).filter(q=>q.booking_id===id).sort((a,b)=>b.revision-a.revision)[0];
export function currentAgreement(operations,id) { return latest(operations,id); }
export function priceFields(agreement,revision=false) {
  return `<fieldset class="admin-price-agreement"><legend>Customer agreement</legend><div class="admin-action-grid">${amountInput('serviceAmount','Service amount (€)',agreement ? (agreement.service_amount_cents/100).toFixed(2) : '')}${amountInput('travelAmount','Travel fee (€), including 0',agreement ? (agreement.travel_amount_cents/100).toFixed(2) : '')}</div><p data-price-total role="status">Enter both agreed amounts.</p><label class="admin-checkbox-row"><input name="customerAgreed" type="checkbox" required><span>I confirm the customer agreed to this final total.</span></label><label data-price-note data-revision="${revision}"${revision ? '' : ' hidden'}>${revision ? 'Reason for revision' : 'Reason for a free service'}<textarea name="priceReason" maxlength="1000"${revision ? ' required' : ''}></textarea></label><small>The final amount includes any VAT selected when invoicing.</small></fieldset>`;
}
export function bindPriceTotals(root) {
  root.querySelectorAll('[name="occurredLocal"],[name="refundOccurredLocal"]').forEach(input=>{
    if(input.dataset.timeChoiceBound) return;input.dataset.timeChoiceBound='true';
    const form=input.form,select=form.elements[input.name==='occurredLocal' ? 'paymentFold' : 'refundFold'];
    if(!select)return;
    const update=()=>{const [day,time]=input.value.split('T'),ambiguous=vilniusCandidates(day || '',time || '').length===2;select.closest('label').hidden=!ambiguous;select.required=ambiguous;if(!ambiguous)select.value='';};
    input.addEventListener('input',update);update();
  });
  root.querySelectorAll('[data-price-total]').forEach(target=>{
    const form=target.closest('form');
    const update=()=>{const service=moneyCents(form.elements.serviceAmount?.value),travel=moneyCents(form.elements.travelAmount?.value);target.textContent=service===null||travel===null ? 'Enter both agreed amounts.' : `Final customer amount: ${money(service+travel)}`;const note=form.querySelector('[data-price-note]');if(note){note.hidden=note.dataset.revision!=='true' && !(service===0 && travel===0);note.querySelector('textarea').disabled=note.hidden;note.querySelector('textarea').required=!note.hidden;}};
    form.addEventListener('input',update);update();
  });
  root.querySelectorAll('[data-action="correctPayment"]').forEach(form=>{
    const movement=form.querySelector('[data-payment-movement]');if(!movement)return;
    const update=()=>{movement.hidden=moneyCents(form.elements.paidAmount.value,true)===0;movement.disabled=movement.hidden;};
    form.addEventListener('input',update);update();
  });
}
export function priceSection(booking,operations,canManage) {
  const quotes=(operations?.quotes || []).filter(q=>q.booking_id===booking.id).sort((a,b)=>b.revision-a.revision), agreement=quotes[0];
  return `<section class="admin-detail-section"><h2>Agreed price</h2>${agreement ? `<p><strong>${money(agreement.total_amount_cents)}</strong> · service ${money(agreement.service_amount_cents)} + travel ${money(agreement.travel_amount_cents)}</p><p>Agreed ${esc(date(agreement.agreed_at))} · revision ${agreement.revision}</p>` : (operations?.detail_pending ? '<p role="status">Loading agreement history…</p>' : '<p role="status">Agreement missing. A staff member must enter the customer’s agreed amounts before further billing.</p>')}${canManage && !operations?.detail_pending && ['confirmed','completed'].includes(booking.status) ? `<details class="admin-disclosure"><summary>${agreement ? 'Record an agreed revision' : 'Record customer agreement'}</summary><form class="admin-action-form" data-admin-action-form data-action="recordAgreedPrice">${hidden('bookingId',booking.id)}${priceFields(agreement,Boolean(agreement))}${formEnd('Save agreed price')}</details>` : ''}${quotes.length ? `<details class="admin-disclosure"><summary>Price history (${quotes.length})</summary>${quotes.map(q=>`<p>Revision ${q.revision}: ${money(q.total_amount_cents)} · ${esc(date(q.agreed_at))}<br>Staff: ${esc(q.agreed_by_staff_id)}${q.revision_reason ? `<br>${esc(q.revision_reason)}` : ''}</p>`).join('')}</details>` : ''}</section>`;
}
function paymentForm(bookingId,kind,entries) {
  const label={recordPayment:'Record money received',recordRefund:'Record a refund',correctPayment:'Correct an entry'}[kind];
  return `<details class="admin-disclosure"><summary>${label}</summary><form class="admin-action-form" data-admin-action-form data-action="${kind}">${hidden('bookingId',bookingId)}${kind==='correctPayment' ? `<label>Original entry<select name="paymentEntryId" required><option value="">Choose an entry</option>${entries.filter(e=>['receipt','refund','opening_receipt'].includes(e.entry_kind)&&!entries.some(r=>r.reverses_entry_id===e.id)).map(e=>`<option value="${esc(e.id)}" data-method="${esc(e.method)}" data-occurred-at="${esc(e.occurred_at)}">${e.occurred_at_is_estimate ? 'Movement date unknown; opening record dated '+esc(date(e.occurred_at)) : esc(date(e.occurred_at))} · ${esc(e.entry_kind)} · ${money(Math.abs(e.signed_amount_cents))}</option>`).join('')}</select></label>` : ''}${amountInput('paidAmount',kind==='correctPayment' ? 'Corrected amount (€), including 0 to reverse a mistake' : 'Actual amount (€)')}<fieldset class="admin-payment-movement-fields" data-payment-movement><label>Payment method<select name="paymentMethod"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="card">Card</option><option value="other">Other</option></select></label><label>${kind==='correctPayment' ? 'Date for the corrected entry (Vilnius)' : 'Date money moved (Vilnius)'}<input name="occurredLocal" type="datetime-local" required></label><label>For a repeated clock-change time<select name="paymentFold"><option value="">Choose if a time repeats</option><option value="first">First occurrence</option><option value="second">Second occurrence</option></select></label></fieldset><label>${kind==='recordPayment' ? 'Note' : 'Reason'}<textarea name="paymentNote" maxlength="1000"${kind==='recordPayment' ? '' : ' required'}></textarea></label>${formEnd(label)}</details>`;
}
export function paymentSection(booking,operations,canBill) {
  const entries=(operations?.payment_entries || []).filter(e=>e.booking_id===booking.id), summary=operations?.payment_summaries?.[booking.id];
  if (!canBill) return '';
  return `<section class="admin-detail-section"><h2>Money received and refunds</h2>${summary ? `<div class="admin-detail-list"><p>Receipts: <strong>${money(summary.received_cents)}</strong></p><p>Refunds: <strong>${money(summary.refunded_cents)}</strong></p><p>Net paid: <strong>${money(summary.net_paid_cents)}</strong></p><p>Remaining: <strong>${summary.agreed_or_invoiced_cents===null ? 'Unknown' : money(summary.remaining_cents)}</strong> · credit ${money(summary.credit_cents)}</p><p>Status: ${esc(String(summary.state || '').replaceAll('_',' '))}</p>${summary.unallocated_cents ? `<p role="alert">${money(summary.unallocated_cents)} has no current invoice allocation. Use it on a later or replacement invoice, or record the actual refund separately.</p>` : ''}</div>` : '<p>Payment balance is unavailable. Refresh before recording money.</p>'}${summary ? [...(['confirmed','completed'].includes(booking.status) ? ['recordPayment'] : []),...(entries.length ? ['recordRefund','correctPayment'] : [])].map(kind=>paymentForm(booking.id,kind,entries)).join('') : ''}<details class="admin-disclosure"><summary>Permanent payment history (${entries.length})</summary>${entries.length ? entries.map(e=>`<article class="admin-mini-item"><div><strong>${esc(String(e.entry_kind).replaceAll('_',' '))}: ${money(e.signed_amount_cents)}</strong><p>${e.occurred_at_is_estimate ? 'Movement date unknown; opening record dated '+esc(date(e.occurred_at)) : esc(date(e.occurred_at))} · ${esc(e.method)} · staff ${esc(e.actor_staff_id || 'Historical opening record')}</p><p>${esc(e.reason || '')}${e.reverses_entry_id ? ' · reversal of '+esc(e.reverses_entry_id) : ''}${e.correction_of_entry_id ? ' · correction of '+esc(e.correction_of_entry_id) : ''}</p></div></article>`).join('') : '<p>No recorded money movements.</p>'}</details></section>`;
}
export function communicationSection(booking,operations) {
  const notifications=(operations?.notifications || []).filter(n=>n.booking_id===booking.id);
  return `<section class="admin-detail-section"><h2>Booking communications</h2><p>Booking status: ${esc(booking.status)}. Saving a booking does not confirm email delivery.</p>${notifications.length ? notifications.map(n=>`<p>${esc(n.kind.replaceAll('_',' '))}: <strong>${esc(n.status)}</strong> · ${esc(date(n.created_at))} · ${esc(n.recipient_email)}${n.human_contact_at ? ' · contacted by staff' : ''}${n.provider_message_id ? `<br>Provider reference: ${esc(n.provider_message_id)}` : ''}</p>`).join('') : (operations?.detail_pending ? '<p>Loading communication history…</p>' : '<p>No verified delivery evidence. Historical “sent” messages mean accepted or unknown.</p>')}</section>`;
}
function noteAction(action,idName,id,label) {
  return `<form class="admin-action-form" data-admin-action-form data-action="${action}">${hidden(idName,id)}<label>${action==='retryNotification' ? 'Reconciliation and reason for a new attempt' : 'Contact method and outcome'}<textarea name="note" required maxlength="1000"></textarea></label>${formEnd(label)}`;
}
